---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-4.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: listenarr
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      listenarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/listenarrs/listenarr
              tag: canary@sha256:0e1bf247a4d606127b6b6782d9fcb86026129c64a2271b3f73c2c235ca1a8bca
            env:
              TZ: Canada/Eastern
              PUID: "568"
              PGID: "568"
              UMASK: "022"
              LISTENARR_PUBLIC_URL: https://listenarr.milton.mcf.io
              LISTENARR_LOG_LEVEL: Information
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 4545
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
        - 100 # nfs.cluster:users
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
        - "{{ .Release.Name }}.milton.mcf.io"
        parentRefs:
        - name: internal
          namespace: ingress-system
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
        - path: /app/config
      media:
        type: nfs
        server: nfs.internal
        path: /media
        globalMounts:
        - path: /audiobooks
          subPath: audiobooks
        - path: /downloads
          subPath: downloads
      tmp:
        type: emptyDir
