---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-vault
  target:
    creationPolicy: Owner
  data:
    - secretKey: hcping_url
      remoteRef:
        key: hcping/url
    - secretKey: pushover_user_key
      remoteRef:
        key: pushover/user_key
    - secretKey: pushover_token
      remoteRef:
        key: pushover/credential
