---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: talos-n150-cluster
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account
          key: credential
          namespace: external-secrets
      cache:
        ttl: 30m # increase ttl to 30 minutes to address rate limiting
