---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      data:
        runner-registration-token: "" # needed for compatibility reasons
        runner-token: "{{ .credential }}"
  data:
  - secretKey: credential
    remoteRef:
      key: gitlab/runner/credential
