---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-runner-cache
spec:
  generateBucketName: cache
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 25G
