---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: openebs-hostpath
