---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
- ../../components/alerts
- ../../components/app-template
resources:
- ./namespace.yaml
- ./coredns/flux-kustomization.yaml
- ./cilium/cilium.yaml
- ./cilium/cilium-config.yaml
- ./multus/multus.yaml
- ./multus/multus-networks.yaml
- ./metrics-server/flux-kustomization.yaml
- ./node-feature-discovery/flux-kustomization.yaml
- ./intel-gpu-resource-driver/flux-kustomization.yaml
- ./descheduler/flux-kustomization.yaml
- ./reloader/flux-kustomization.yaml
- ./spegel/flux-kustomization.yaml
- ./snapshot-controller/flux-kustomization.yaml
