---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./oci-repository.yaml
  - ./external-secret.yaml
  - ./external-secret-oidc.yaml
  - ./helm-release.yaml
  - ./http-route-external.yaml
  - ./http-route-internal.yaml
  - ./tcp-route.yaml
  - ./cilium-network-policy.yaml
