---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${volume_name:=${app}}
spec:
  accessModes:
    - ${volume_accessmodes:=ReadWriteOnce}
  dataSourceRef:
    kind: Restore
    apiGroup: kopiur.home-operations.com
    name: ${app}
  resources:
    requests:
      storage: ${volume_capacity:=1Gi}
  storageClassName: ${volume_storageclass:=ceph-replicated}
