---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: prometheus-remote-write
spec:
  config:
    receivers:
      prometheusremotewrite:
        endpoint: 0.0.0.0:9090

    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s

    exporters:
      otlp_http:
        endpoint: http://123633596.otel.gitlab-o11y.com:4318
        tls:
          insecure: true
      otlp_grpc:
        endpoint: http://123633596.otel.gitlab-o11y.com:4317
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers:
          - prometheusremotewrite
          processors:
          - batch
          exporters:
          - otlp_http
