---
spec:
  inputs:
    schemas:
      description: Generate and publish JSON schemas from CRDs
      type: boolean
      default: false
    renovate:
      description: Run Renovate to update dependencies
      type: boolean
      default: false

---
# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
stages:
- lint
- build
- test
- deploy
- renovate

include:
- .gitlab/ci/labels.yaml
- .gitlab/ci/lint.yaml
- .gitlab/ci/flux-local.yaml
- local: .gitlab/ci/renovate.yaml
  rules:
  - if: $[[ inputs.renovate ]] == true
  - if: $CI_PIPELINE_SOURCE == "push"
    changes:
      paths:
      - .gitlab/renovate.json
      - .renovate/**/*
- local: .gitlab/ci/schemas.yaml
  rules:
  - if: $[[ inputs.schemas ]] == true
