---
# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
stages:
- lint
- test
- renovate

variables:
  CI_MISE_IMAGE: ghcr.io/jdx/mise:2026.6@sha256:6dac17a05e767152c5f0367d90613d69c81e05420bb226467d04c57d843bdbba

.mise:
  variables:
    MISE_ENV: gitlab-ci
    MISE_DATA_DIR: $CI_PROJECT_DIR/.cache/mise
    UV_LINK_MODE: copy
  image: $CI_MISE_IMAGE
  cache:
    key:
      files:
      - .mise.lock
      - .mise.gitlab-ci.toml
    paths:
    - .cache/mise/
  before_script:
  - mise install
  - eval "$(mise activate bash --shims)"

include:
- .gitlab/ci/labels.yaml
- .gitlab/ci/lint.yaml
- .gitlab/ci/flate.yaml
- .gitlab/ci/renovate.yaml
