[pre-commit]
parallel = true
skip = ["merge", "rebase"]

[pre-commit.commands.format-toml]
glob = ["*.toml"]
run = "for file in {staged_files}; do tombi format $file; done"
stage_fixed = true

[pre-commit.commands.format-yaml]
glob = ["*.yaml", "*.yml"]
run = "yamlfmt {staged_files}"
stage_fixed = true

[pre-commit.commands.lint-yaml]
glob = ["*.yaml", "*.yml"]
run = "yamllint --config-file .yamllint.yaml {staged_files}"

[pre-commit.commands.format-mise]
glob = [".mise/config.toml"]
run = "mise fmt"
stage_fixed = true

[pre-commit.commands.mise-lock]
glob = [".mise/config.toml"]
run = 'mise lock && { for f in {staged_files}; do l="$(dirname "$f")/mise.lock"; [ -f "$l" ] && git add "$l"; done; true; }'
