#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json
#

experimental_monorepo_root = true

[settings]
experimental = true
unix_default_inline_shell_args = "bash -euo pipefail -c"
env_shell_expand = true

[monorepo]
config_roots = ["kubernetes", "talos"]

[env]
_.file = ["{{ config_root }}/.secrets.env"]
MINIJINJA_CONFIG_FILE = "{{ config_root }}/.minijinja.toml"
TALOSCONFIG = "{{ config_root }}/talosconfig"
KUBECONFIG = "{{ config_root }}/kubeconfig"

[tools]
"aqua:gum" = "latest"
"aqua:lefthook" = "latest"
"aqua:shellcheck" = "latest"
"aqua:tombi" = "latest"
"aqua:uv" = "latest"
"aqua:yq" = "latest"
"pipx:flux-local" = "latest"

"github:postfinance/topf" = "0.4.0-rc.1"
"aqua:helmfile/vals" = "v0.44.0"
"aqua:helm" = "latest"
"aqua:helm-ls" = "latest"
