---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
spec:
  instances: 1
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10-standard-trixie
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: ceph-replicated
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-postgres-app
  postgresql:
    parameters:
      max_connections: "100"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
