---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: internal
spec:
  http2:
    onInvalidMessage: TerminateStream
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
  tcpKeepalive:
    idleTime: 60s
    interval: 10s
    probes: 3
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
