---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopiur-mover-restores-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopiur-mover-restores-read
subjects:
  - kind: ServiceAccount
    name: kopiur-mover
    namespace: default
  - kind: ServiceAccount
    name: kopiur-mover
    namespace: kopiur-system
