---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: RADARR__APIKEY
    # remoteRef:
    #   key: arr-stack-apikeys
    #   property: RADARR_CREDENTIAL
    remoteRef:
      key: arr-stack-apikeys/radarr/credential
  - secretKey: SONARR__APIKEY
    # remoteRef:
    #   key: arr-stack-apikeys
    #   property: SONARR_CREDENTIAL
    remoteRef:
      key: arr-stack-apikeys/sonarr/credential
