---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kopia
spec:
  components:
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: volsync
    - name: nfs-server
      namespace: default
  interval: 12h
  path: ./kubernetes/apps/volsync-system/kopia/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: volsync-system
  wait: false
  postBuild:
    substitute:
      app: *appname
