---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopia-maintenance
spec:
  dependsOn:
    - name: kopia
  interval: 12h
  path: ./kubernetes/apps/volsync-system/kopia/maintenance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: volsync-system
  wait: false
