---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-zone
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: credential
    remoteRef:
      key: cloudflare
      property: DNS_ZONE_EDIT_CREDENTIAL
    # remoteRef:
    #   key: cloudflare/dns-zone-edit/credential
