---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel
    template:
      data:
        CLOUDFLARE_TUNNEL_ID: |
          {{ .tunnel_id }}
        TUNNEL_TOKEN: |
          {{ .tunnel_token }}
  data:
    - secretKey: tunnel_id
      remoteRef:
        key: CLOUDFLARE_TUNNEL_ID
    - secretKey: tunnel_token
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN
