---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/cilium.io/ciliumnodeconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: qemu
spec:
  nodeSelector:
    matchLabels:
      io.cilium.node-config/name: qemu
  defaults:
    devices: eth+,vlan+
---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/cilium.io/ciliumnodeconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: rpi
spec:
  nodeSelector:
    matchLabels:
      io.cilium.node-config/name: rpi
  defaults:
    devices: end+,vlan+
