---
metrics: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/30387687?v=4
  link: https://github.com/mcfio
  default-sort-by: group
  buttons:
    - name: GitHub
      link: https://github.com/mcfio/talos-n150-cluster

web:
  port: ${WEB_PORT}

storage:
  type: sqlite
  path: ${GATUS_CONFIG_PATH}/gatus.db
  caching: true

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: internal-dns
    group: dns
    url: 192.168.10.1
    interval: 60s
    dns:
      query-name: ipv4.milton.mcf.io
      query-type: A
    conditions:
      - "[DNS_RCODE] == NOERROR"
      - "[BODY] == 192.168.46.96"

  - name: public-dns
    group: dns
    url: 9.9.9.9
    interval: 120s
    dns:
      query-name: status.mcf.io
      query-type: A
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: dnssec-validation
    group: dns
    url: 192.168.10.1
    interval: 300s
    dns:
      query-name: dnssec-failed.org
      query-type: A
    conditions:
      - "[DNS_RCODE] == SERVFAIL"

  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
