---
machine:
  type: controlplane
  install:
    diskSelector:
      type: ssd
  kernel:
    modules:
      - name: nfsd
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk1
discovery:
  volumeSelector:
    match: volume.label == "media-disk1"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk2
discovery:
  volumeSelector:
    match: volume.label == "media-disk2"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk3
discovery:
  volumeSelector:
    match: volume.label == "media-disk3"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk4
discovery:
  volumeSelector:
    match: volume.label == "media-disk4"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk5
discovery:
  volumeSelector:
    match: volume.label == "media-disk5"
