---
machine:
  type: controlplane
  install:
    diskSelector:
      type: nvme
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-node03
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  maxSize: 250GiB
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: csi-data
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  minSize: 250GiB
  grow: true
