---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
machine:
  type: worker
  install:
    diskSelector:
      type: nvme
    image: factory.talos.dev/metal-installer-secureboot/46302451fc0b28c9baf2854ed7b740565ec3b640e1dbf232ffed54de870a21b7:v1.13.0
  nodeLabels:
    node.kubernetes.io/intel-gpu: "true"
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-node03
---
apiVersion: v1alpha1
kind: VLANConfig
name: vlan10
vlanID: 10
vlanMode: 802.1q
parent: primary0
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  maxSize: 250GiB
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: csi-data
provisioning:
  diskSelector:
    match: disk.transport == "nvme"
  minSize: 250GiB
  grow: true
---
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
timeout: 5m
