---
machine:
  type: worker
  nodeLabels:
    mcf.io/role: storage
  kubelet:
    extraConfig:
      registerWithTaints:
        - key: mcf.io/role
          value: storage
          effect: PreferNoSchedule
  install:
    diskSelector:
      type: ssd
  kernel:
    modules:
      - name: nfsd
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-stor01
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk1
discovery:
  volumeSelector:
    match: volume.label == "media-disk1"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk2
discovery:
  volumeSelector:
    match: volume.label == "media-disk2"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk3
discovery:
  volumeSelector:
    match: volume.label == "media-disk3"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk4
discovery:
  volumeSelector:
    match: volume.label == "media-disk4"
---
apiVersion: v1alpha1
kind: ExistingVolumeConfig
name: media-disk5
discovery:
  volumeSelector:
    match: volume.label == "media-disk5"
