---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
machine:
  type: controlplane
  install:
    disk: /dev/sda
    image: factory.talos.dev/metal-installer-secureboot/96b1e5cb9cca4d90b385954c9e3766be4b529c900ccdef1824ba31b94c062d4e:v1.12.5
  nodeLabels:
    io.cilium.node-config/name: qemu
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
---
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
timeout: 5m
