---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
- ../../components/alerts
- ../../components/app-template
- ../../components/gpu
resources:
- ./namespace.yaml
- ./sonarr/app.yaml
- ./radarr/app.yaml
- ./listenarr/app.yaml
- ./litellm/app.yaml
- ./litellm-db/app.yaml
- ./maintainerr/app.yaml
- ./nfs-server/app.yaml
- ./prowlarr/app.yaml
- ./sabnzbd/app.yaml
- ./plex/app.yaml
- ./gatus/app.yaml
- ./tautulli/app.yaml
- ./recyclarr/app.yaml
- ./seerr/app.yaml
- ./mosquitto/app.yaml
- ./home-assistant/app.yaml
- ./matter-server/flux-kustomization.yaml
- ./scrypted/app.yaml
- ./zwave/app.yaml
