---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-environment
  target:
    creationPolicy: Owner
  data:
    - secretKey: masterkey
      remoteRef:
        key: LITELLM_MASTERKEY
    - secretKey: TAVILY_API_KEY
      remoteRef:
        key: TAVILY_API_KEY
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: ANTHROPIC_API_KEY
