---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-cache
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
