---
.flux-local:
  variables:
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1 # necessary for git safe.directory
  stage: flux-local
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    changes:
    - kubernetes/**/*.yaml
  image:
    name: ghcr.io/allenporter/flux-local:v8.1.0@sha256:37c3c4309a351830b04f93c323adfcb0e28c368001818cd819cbce3e08828261
    entrypoint:
    - ""

.flux-local_matrix: &flux-local_matrix
  parallel:
    matrix:
    - RESOURCE:
      - kustomization
      - helmrelease

flux-local:test:
  extends:
  - .flux-local
  script: |
    flux-local test \
      --all-namespaces \
      --enable-helm \
      --path "${CI_PROJECT_DIR}/kubernetes/flux/config" \
      --verbose

flux-local:diff:
  extends:
  - .flux-local
  <<: *flux-local_matrix
  before_script:
  - git clone --depth=1 "${CI_PROJECT_URL}" "${CI_BUILDS_DIR}/${CI_DEFAULT_BRANCH}-worktree"
  - mkdir -p "${CI_PROJECT_DIR}/diff_outputs"
  script: |
    flux-local diff "${RESOURCE}" \
      --unified 6 \
      --path "${CI_PROJECT_DIR}/kubernetes/flux/config" \
      --path-orig "${CI_BUILDS_DIR}/${CI_DEFAULT_BRANCH}-worktree/kubernetes/flux/config" \
      --strip-attrs "helm.sh/chart,checksum/config,app.kubernetes.io/version,chart" \
      --limit-bytes 10000 \
      --all-namespaces \
      --sources "flux-system" \
      --output-file "${CI_PROJECT_DIR}/diff_outputs/${RESOURCE}.output"
  artifacts:
    paths:
    - $CI_PROJECT_DIR/diff_outputs/

flux-local:notes:
  stage: flux-local
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    changes:
    - kubernetes/**/*.yaml
  needs:
  - job: flux-local:diff
    artifacts: true
  image: registry.gitlab.com/gitlab-org/cli:v1.87.0@sha256:366e13e3d99a63e66ec186111728031343ef994cc0e3fc4ca1bfafc65f5dec25
  variables:
    GITLAB_TOKEN: $CI_BOT_JOB_TOKEN
  script: |
    for resource in kustomization helmrelease; do
      if [[ -s "${CI_PROJECT_DIR}/diff_outputs/${resource}.output" ]]; then
        echo '```diff' > "${CI_PROJECT_DIR}/diff_outputs/${resource}.md"
        cat "${CI_PROJECT_DIR}/diff_outputs/${resource}.output" >> "${CI_PROJECT_DIR}/diff_outputs/${resource}.md"
        echo '```' >> "${CI_PROJECT_DIR}/diff_outputs/${resource}.md"
        glab mr note "${CI_MERGE_REQUEST_IID}" --repo "${CI_PROJECT_PATH}" --unique --message "$(cat "${CI_PROJECT_DIR}"/diff_outputs/${resource}.md)"
      fi
    done
