---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-postgres
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  interval: 12h
  path: ./kubernetes/apps/forgejo-system/postgres/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo-system
  wait: true
  timeout: 10m
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.phase == 'Cluster is unrecoverable and needs manual intervention'
      current: status.phase == 'Cluster in healthy state'
