---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/tags/v1.14.0/website/content/v1.14/schemas/config.schema.json
version: v1alpha1
machine:
  ca:
    crt: op://milton-ops/talos-n150-cluster/machine/ca_crt
    key: op://milton-ops/talos-n150-cluster/machine/ca_key
cluster:
  etcd:
    ca:
      crt: op://milton-ops/talos-n150-cluster/etcd/ca_crt
      key: op://milton-ops/talos-n150-cluster/etcd/ca_key
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
      heartbeat-interval: "250"
      election-timeout: "2500"
      snapshot-count: "10000"
      quota-backend-bytes: "2147483648"
      max-concurrent-streams: "1000"
    advertisedSubnets:
      - 192.168.45.0/24
---
apiVersion: v1alpha1
kind: KubeAPIServerCAConfig
issuingCA:
  cert: "op://milton-ops/talos-n150-cluster/cluster/ca_crt_pem" # yamllint disable-line rule:quoted-strings
  key: "op://milton-ops/talos-n150-cluster/cluster/ca_key_pem" # yamllint disable-line rule:quoted-strings
---
apiVersion: v1alpha1
kind: KubeAggregatorCAConfig
issuingCA:
  cert: "op://milton-ops/talos-n150-cluster/cluster/aggregator_ca_crt_pem" # yamllint disable-line rule:quoted-strings
  key: "op://milton-ops/talos-n150-cluster/cluster/aggregator_ca_key_pem" # yamllint disable-line rule:quoted-strings
---
apiVersion: v1alpha1
kind: KubeServiceAccountConfig
issuer:
  privateKey: "op://milton-ops/talos-n150-cluster/cluster/service_account_key_pem" # yamllint disable-line rule:quoted-strings
  issuerURL: https://k8s.internal:6443
---
apiVersion: v1alpha1
kind: KubeEtcdEncryptionConfig
config:
  resources:
    - resources:
        - secrets
      providers:
        - secretbox:
            keys:
              - name: key2
                secret: op://milton-ops/talos-n150-cluster/cluster/secretbox_encryption_secret
        - identity: {}
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:admin
allowedKubernetesNamespaces:
  - system-upgrade
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
image: registry.k8s.io/kube-apiserver:v1.36.4
extraArgs:
  enable-aggregator-routing: "true"
  feature-gates: VolumeLimitScaling=true
certExtraSANs:
  - k8s.internal
---
apiVersion: v1alpha1
kind: KubeAuditPolicyConfig
configuration:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    - level: Metadata
---
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    conditions:
      - path: /livez
      - path: /readyz
      - path: /healthz
    enabled: true
  jwt: []
---
apiVersion: v1alpha1
kind: KubeAuthorizerConfig
name: node
type: Node
---
apiVersion: v1alpha1
kind: KubeAuthorizerConfig
name: rbac
type: RBAC
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
image: registry.k8s.io/kube-controller-manager:v1.36.4
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
image: registry.k8s.io/kube-scheduler:v1.36.4
extraArgs:
  bind-address: 0.0.0.0
  feature-gates: VolumeLimitScaling=true
config:
  profiles:
    - schedulerName: default-scheduler
      plugins:
        score:
          disabled:
            - name: ImageLocality
      pluginConfig:
        - name: PodTopologySpread
          args:
            defaultingType: List
            defaultConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  node-role.kubernetes.io/control-plane: ""
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.45.70
link: primary0
