---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.13/website/content/v1.13/schemas/config.schema.json
version: v1alpha1
machine:
  ca:
    crt: op://mcfio/talos-n150-cluster/machine/ca_crt
    key: op://mcfio/talos-n150-cluster/machine/ca_key
  features:
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:admin
      allowedKubernetesNamespaces:
        - system-upgrade
cluster:
  ca:
    crt: op://mcfio/talos-n150-cluster/cluster/ca_crt
    key: op://mcfio/talos-n150-cluster/cluster/ca_key
  aggregatorCA:
    crt: op://mcfio/talos-n150-cluster/cluster/aggregator_ca_crt
    key: op://mcfio/talos-n150-cluster/cluster/aggregator_ca_key
  serviceAccount:
    key: op://mcfio/talos-n150-cluster/cluster/service_account_key
  secretboxEncryptionSecret: op://mcfio/talos-n150-cluster/cluster/secretbox_encryption_secret
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.37.0
    extraArgs:
      enable-aggregator-routing: "true"
    certSANs:
      - k8s.internal
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
    image: registry.k8s.io/kube-controller-manager:v1.37.0
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.37.0
    extraArgs:
      bind-address: 0.0.0.0
    config:
      apiVersion: kubescheduler.config.k8s.io/v1
      kind: KubeSchedulerConfiguration
      profiles:
        - schedulerName: default-scheduler
          plugins:
            score:
              disabled:
                - name: ImageLocality
          pluginConfig:
            - name: PodTopologySpread
              args:
                defaultingType: List
                defaultConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
  allowSchedulingOnControlPlanes: true
  coreDNS:
    disabled: true
  etcd:
    ca:
      crt: op://mcfio/talos-n150-cluster/etcd/ca_crt
      key: op://mcfio/talos-n150-cluster/etcd/ca_key
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
      heartbeat-interval: "250"
      election-timeout: "2500"
      snapshot-count: "10000"
      quota-backend-bytes: "2147483648"
      max-concurrent-streams: "1000"
    advertisedSubnets:
      - 192.168.45.0/24
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.45.70
link: primary0
