---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: PROWLARR__AUTH__APIKEY
    remoteRef:
      key: arr-stack-apikeys
      property: PROWLARR_CREDENTIAL
    # remoteRef:
    #   key: arr-stack-apikeys/prowlarr/credential
