#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json
#

experimental_monorepo_root = true

[settings]
experimental = true
unix_default_inline_shell_args = "bash -euo pipefail -c"
env_shell_expand = true
lockfile = true

[monorepo]
config_roots = ["kubernetes", "talos"]

[env]
_.file = ["{{ config_root }}/.secrets.env"]
HK_MISE = 1
FLATE_PATH = "{{ config_root }}/kubernetes/flux/config"
TALOSCONFIG = "{{ config_root }}/talosconfig"
KUBECONFIG = "{{ config_root }}/kubeconfig"

[tools]
"github:home-operations/flate" = "v0.4.0"
"jq" = "1.8.1"
"uv" = "0.11.20"
"glab" = "1.101.0"
"yamllint" = "1.38.0"
