---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-system
components:
- ../../components/alerts
- ../../components/app-template
resources:
- ./namespace.yaml
- ./external-dns/cloudflare.yaml
- ./external-dns/unifi.yaml
- ./cloudflare-tunnel/app.yaml
- ./internal-proxy/app.yaml
- ./external-proxy/app.yaml
