---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-runner
    creationPolicy: Owner
    template:
      data:
        config.yaml: |
          runner:
            capacity: 4
            timeout: 3h
            shutdown_timeout: 3h
            fetch_timeout: 30s
            fetch_interval: 2s
            labels:
              - cli:host
          cache:
            enabled: false
          host:
            workdir_parent: ""
          server:
            connections:
              forgejo:
                url: http://forgejo-http.forgejo-system.svc:3000/
                uuid: {{ .uuid }}
                token: {{ .token }}
                labels:
                  - cli:host
  data:
    - secretKey: uuid
      remoteRef:
        key: forgejo-runner/uuid
    - secretKey: token
      remoteRef:
        key: forgejo-runner/token
