---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm-db
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: cnpg-cluster
  values:
    version:
      postgresql: "18"
    cluster:
      instances: 1
      enablePDB: false
      switchoverDelay: 40
      storage:
        size: 5Gi
      postgresql:
        parameters:
          max_connections: "200"
      monitoring:
        enabled: false
    # backups:
    #   enabled: false
    #   endpointURL: https://<account-id>.r2.cloudflarestorage.com
    #   destinationPath: s3://litellm-db-backups/
    #   provider: s3
    #   secret:
    #     create: false
    #     name: litellm-db-r2-credentials
    #   scheduledBackup:
    #     name: daily-backup
    #     schedule: "0 2 * * *"
    #     backupOwnerReference: self
