---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-maintenance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    template:
      data:
        KOPIA_FS_PATH: /repository/kopia
        KOPIA_PASSWORD: "{{ .credential }}"
        KOPIA_REPOSITORY: filesystem:///repository/kopia
  data:
  - secretKey: credential
    remoteRef:
      key: volsync
      property: KOPIA_PASSWORD
    # remoteRef:
    #   key: volsync/kopia/credential
