---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: lint
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # renovate: datasource=github-releases depName=adrienverge/yamllint
      - name: Setup Mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          cache: false
          tool_versions: |
            yamllint 1.38.0

      - name: Run Yamllint
        run: yamllint --config-file .yamllint.yaml --format github .
