---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/cilium.io/ciliumnodeconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: vmware-node-config
spec:
  nodeSelector:
    matchLabels:
      node.cloudprovider.kubernetes.io/platform: vmware
      kubernetes.io/arch: amd64
  defaults:
    devices: eth+
---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/cilium.io/ciliumnodeconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: rpi-node-config
spec:
  nodeSelector:
    matchLabels:
      node.cloudprovider.kubernetes.io/platform: metal
      kubernetes.io/arch: arm64
  defaults:
    devices: end+
